[phases.setup]
nixPkgs = ["nodejs_20", "npm", "php83", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction",
  "npm ci --only=production --no-audit",
  "npm run build"
]

[phases.build]
cmds = [
  "chmod +x deploy.sh",
  "./deploy.sh"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
